#!/bin/bash

args=$@

total() {
    total=0
    for i in ${rolls[@]:0:$1}; do
        let total+=$i
    done
    if [[ $add != $args ]]; then
        let total+=$add
        modifier="+"$add
    fi
    if [[ $sub != $args ]]; then
        let total-=$sub
        modifier="-"$sub
    fi
    echo -e '\e[1m'$total'\e[22m' "("$(echo ${rolls[@]:0:$1} | sed -e 's/ /\+/g')")$modifier "'\e[9m'$removed'\e[29m'
}

count=$(echo $1 | sed -e 's/\([0-9]*\)d.*/\1/g')
if [[ $count = "" ]]; then
    count=1
fi

faces=$(echo $1 | sed -e 's/.*d\([0-9]*\).*/\1/g')
if [[ $faces = "" ]]; then
    echo "Syntax: roll [dice_count]d[die_sides] "
    echo ""
    echo "OPTIONS:"
    echo "h(igh) # — Keep only the # highest dice."
    echo "l(ow) # — Keep only the # lowest dice."
    echo "+# — Add # to the total."
    echo "-# — Subtract from the total."
    echo ""
    echo "Syntax is flexible: You can add spaces and full words, or just use single letters — whatever is intuitive for you."
    echo "ie: 'h2' and 'high 2' and 'keep the highest 2' will all do the same thing."
    echo "tldr example: roll 5d6 h2 +3 — 'Roll five 6-sided dice, keep the highest 2, add 3.'"
    exit
fi

add=$(echo $@ | sed -e 's/.*+ *\([0-9]\+\).*/\1/g')
sub=$(echo $@ | sed -e 's/.*- *\([0-9]\+\).*/\1/g')
high=$(echo $@ | sed -e 's/.*h[a-z]* *\([0-9]\+\).*/\1/g')
low=$(echo $@ | sed -e 's/.*l[a-z]* *\([0-9]\+\).*/\1/g')

rolls=()
countrolls=$count
while [[ $countrolls > 0 ]]; do
    rolls+=(" $((1 + $RANDOM % $faces))")
    let countrolls=$countrolls-1
done

if [[ $high != $@ ]]; then
    IFS=$'\n' rolls=($(sort -nr <<<"${rolls[*]}"))
    unset IFS
    removed="("$(echo ${rolls[@]:$high:${#rolls[@]}} | sed -e 's/ /\+/g')")"
    total $high
elif [[ $low != $@ ]]; then
    IFS=$'\n' rolls=($(sort -n <<<"${rolls[*]}"))
    unset IFS
    removed="("$(echo ${rolls[@]:$low:${#rolls[@]}} | sed -e 's/ /\+/g')")"
    total $low
else
    total $count
fi
